In [1]:
import numpy as np

In [2]:
array_3d = np.random.randint(1, 100, size=(3, 3, 3))

In [7]:
array_3d.shape

(3, 3, 3)

In [8]:
array_3d

array([[[70, 43,  7],
        [63, 66, 85],
        [70,  6, 74]],

       [[21, 90,  2],
        [ 5, 45, 57],
        [16, 58, 88]],

       [[ 1, 38, 87],
        [13, 14, 60],
        [64, 64, 24]]])

In [28]:
array_3d[1][1][1]

45

In [30]:
array_3d[2][1][0]

13

In [15]:
a=np.eye(5)*5
b =np.triu(a)+1

In [35]:
b=np.triu(np.ones((5,5)),k=1)
a+=b
a

array([[5., 1., 1., 1., 1.],
       [0., 5., 1., 1., 1.],
       [0., 0., 5., 1., 1.],
       [0., 0., 0., 5., 1.],
       [0., 0., 0., 0., 5.]])

In [25]:
matrix=np.eye(5)*5

In [36]:
for i in range(5):
    for j in range(i+1, 5):
        matrix[i, j] = 1
        #print(i,j)

In [27]:
matrix

array([[5., 1., 1., 1., 1.],
       [0., 5., 1., 1., 1.],
       [0., 0., 5., 1., 1.],
       [0., 0., 0., 5., 1.],
       [0., 0., 0., 0., 5.]])